# Copyright (c) 2012 Justin Ethier
# This file and all modifications and additions to the pristine
# package are under the same license as the package itself.
#
# Please submit bugfixes or comments to Justin Ethier via https://github.com/justinethier/husk-scheme
 
# norootforbuild
 
%define pkg_name husk-scheme

%global common_summary An R5RS-compatible Scheme written in Haskell

%global common_description An R5RS Scheme interpreter, compiler, and library written in Haskell. \
Provides advanced features including continuations, \
non-hygienic macros, a Haskell FFI, and the full numeric tower.\
 
# ghc does not emit debug information
%define debug_package %{nil}
 
Name:           ghc-%{pkg_name}
Version:        3.5.3.2
Release:        1%{?dist}
Summary:        %{common_summary}

Group:          Compilers/Interpreters, Language
License:        MIT
URL:            http://hackage.haskell.org/package/%{pkg_name}
Source0:        http://hackage.haskell.org/packages/archive/%{pkg_name}/%{version}/%{pkg_name}-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root
ExclusiveArch:  %{ghc_arches}
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
#?? BuildRequires:  hscolour
BuildRequires:  ghc, ghc-doc, ghc-prof
BuildRequires:  ghc-parsec-devel ghc-haskeline-devel ghc-ghc-paths-devel
BuildRequires:  ghc-ghc-devel

%description
%{common_description}
 

%prep
%setup -q


%build
%ghc_lib_build


%install
%ghc_lib_install


# library subpackage
%ghc_package

%ghc_description


# devel subpackage
%ghc_devel_package

%ghc_devel_description


%ghc_devel_post_postun


%files
%doc LICENSE
%attr(755,root,root) %{_bindir}/%{name}


%ghc_files


%changelog
* Thu Mar  8 2012 Fedora Haskell SIG <haskell-devel@lists.fedoraproject.org>
- spec file template generated by cabal2spec-0.25.4
