# Run a "simple" build using GHC directly 
husk: hs-src/shell.hs hs-src/Scheme/Core.hs hs-src/Scheme/Macro.hs hs-src/Scheme/Numerical.hs hs-src/Scheme/Parser.hs hs-src/Scheme/Types.hs hs-src/Scheme/Variables.hs
	ghc -Wall --make -package parsec -fglasgow-exts -o huski hs-src/shell.hs hs-src/Scheme/Core.hs hs-src/Scheme/Macro.hs hs-src/Scheme/Numerical.hs hs-src/Scheme/Parser.hs hs-src/Scheme/Types.hs hs-src/Scheme/Variables.hs Paths_husk_scheme.hs

# Create files for distribution
dist:
	runhaskell Setup.hs configure --prefix=$(HOME) --user && runhaskell Setup.hs build && runhaskell Setup.hs install && runhaskell Setup.hs sdist

# Create API documentation
doc:
	runhaskell Setup.hs haddock 

# Run all unit tests
test:
#	cd scm-unit-tests ; ../huski t-backquote.scm
	cd scm-unit-tests ; ../huski t-case.scm
	cd scm-unit-tests ; ../huski t-cond.scm
	cd scm-unit-tests ; ../huski t-delay.scm
	cd scm-unit-tests ; ../huski t-iteration.scm
	cd scm-unit-tests ; ../huski t-macro.scm
	cd scm-unit-tests ; ../huski t-numerical-ops.scm
	cd scm-unit-tests ; ../huski t-hashtable.scm
	cd scm-unit-tests ; ../huski t-special-forms.scm
	cd scm-unit-tests ; ../huski t-standard-procedures.scm
	cd scm-unit-tests ; ../huski t-stdlib.scm
	cd scm-unit-tests ; ../huski t-string.scm
	cd scm-unit-tests ; ../huski t-vector.scm
	cd scm-unit-tests ; ../huski t-exec.scm
	cd scm-unit-tests ; ../huski t-cont.scm
	cd scm-unit-tests ; ../huski t-backquote.scm

# Delete all temporary files generated by a build
clean:
	rm -f *.o
	rm -f hs-src/*.o
	rm -f hs-src/Scheme/*.o
	rm -f *.hi
	rm -f hs-src/*.hi
	rm -f hs-src/Scheme/*.hi
	rm -f huski
	rm -rf dist
